import { useApp } from "../context/AppContext";
import { TrendingUp, ShieldCheck } from "lucide-react";

interface PlanDisplayProps {
  onSelectPlanIndex?: (index: number) => void;
  selectedPlanIndex?: number;
}

export default function PlanDisplay({ onSelectPlanIndex, selectedPlanIndex = 0 }: PlanDisplayProps) {
  const { state } = useApp();
  const activeId = state.selectedDisruptionId;
  const plans = activeId ? state.plans[activeId] ?? [] : [];

  const renderParamsTable = (params: Record<string, unknown>) => {
    const keys = Object.keys(params);
    if (keys.length === 0)
      return <span className="text-ink-soft italic text-[11px]">None</span>;
    return (
      <table className="w-full text-[10px] font-mono border border-cream-deep/60 rounded overflow-hidden">
        <tbody>
          {keys.map((k) => (
            <tr key={k} className="border-b border-cream-deep/40 bg-cream/30">
              <td className="px-2 py-1 font-bold text-ink-soft border-r border-cream-deep/40 bg-cream-deep/10 w-20 capitalize">
                {k.replace(/_/g, " ")}
              </td>
              <td className="px-2 py-1 text-ink break-all">
                {Array.isArray(params[k])
                  ? (params[k] as unknown[]).join(" → ")
                  : String(params[k])}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  if (!activeId) {
    return (
      <div className="glass rounded-2xl p-6 h-[200px] flex items-center justify-center text-ink-soft text-sm">
        Select a disruption to view solver optimization options.
      </div>
    );
  }

  if (plans.length === 0) {
    return (
      <div className="glass rounded-2xl p-6 h-[200px] flex items-center justify-center text-ink-soft text-sm">
        No candidate plans generated yet. Solver planning in progress…
      </div>
    );
  }

  return (
    <div className="glass rounded-2xl p-6 flex flex-col space-y-4">
      <div className="border-b border-cream-deep pb-3">
        <h3 className="font-serif text-xl font-semibold text-ink flex items-center gap-2">
          <TrendingUp className="w-5 h-5 text-gold" />
          Solver Optimization Plans
        </h3>
        <p className="text-xs text-ink-soft">Side-by-side alternatives generated by OR-Tools.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {plans.map((plan, pIdx) => {
          const isSelected = selectedPlanIndex === pIdx;
          const optionLabel = String.fromCharCode(65 + pIdx); // A, B, C …
          return (
            <div
              key={pIdx}
              onClick={() => onSelectPlanIndex && onSelectPlanIndex(pIdx)}
              className={`p-5 rounded-2xl border transition-all duration-300 cursor-pointer flex flex-col justify-between ${
                isSelected
                  ? "bg-white border-sakura shadow-md ring-2 ring-sakura/20 scale-[1.005]"
                  : "bg-white/50 border-cream-deep hover:bg-white hover:border-sakura/30 shadow-sm"
              }`}
            >
              <div>
                <div className="flex justify-between items-start mb-3">
                  <div>
                    <h4 className="font-bold text-sm text-ink">Option {optionLabel}</h4>
                    <span className="text-[10px] font-mono text-ink-soft block mt-0.5">
                      Score:{" "}
                      <strong className="text-emerald-600">
                        {(plan.score * 100).toFixed(0)}%
                      </strong>
                    </span>
                  </div>
                  <div className="text-right">
                    <span className="block font-bold text-md text-red font-mono">
                      ${plan.total_cost.toLocaleString()}
                    </span>
                    <span className="block text-[10px] text-ink-soft font-mono">
                      Est. {plan.est_time_min} min
                    </span>
                  </div>
                </div>

                <p className="text-xs text-ink-soft leading-relaxed italic mb-4 bg-cream/40 p-2 rounded-lg border border-cream-deep/30">
                  "{plan.rationale}"
                </p>

                <div className="space-y-3">
                  <h5 className="font-mono text-[9px] uppercase tracking-wider text-ink-soft/75 border-b border-cream-deep/40 pb-1">
                    Action Pipeline
                  </h5>
                  {plan.steps.map((step, sIdx) => (
                    <div
                      key={sIdx}
                      className="space-y-1 bg-cream-deep/20 p-2.5 rounded-xl border border-cream-deep/20"
                    >
                      <div className="flex items-center justify-between text-xs">
                        <span className="font-semibold text-ink capitalize flex items-center gap-1">
                          <span
                            className={`w-1.5 h-1.5 rounded-full ${
                              step.reversible ? "bg-emerald-400" : "bg-red"
                            }`}
                          />
                          {step.action.replace(/_/g, " ")}
                        </span>
                        <span className="text-[10px] font-mono text-ink-soft">{step.target}</span>
                      </div>
                      <div className="mt-1.5">{renderParamsTable(step.params)}</div>
                      <div className="flex justify-between text-[9px] font-mono text-ink-soft/80 mt-1">
                        <span>Cost: ${step.est_cost}</span>
                        <span className={step.reversible ? "text-emerald-600" : "text-red font-bold"}>
                          {step.reversible ? "Reversible" : "Irreversible (PO)"}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {isSelected && (
                <div className="mt-4 pt-3 border-t border-cream-deep/50 flex items-center gap-1.5 text-[11px] text-emerald-600 font-semibold">
                  <ShieldCheck className="w-4 h-4" /> Selected Proposal
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
